author:
  name2: beibei
  age2: 2
feign:
  client:
    url: 192.168.3.61:8080
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
spring:
  application:
    name: springboot-feign
